config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  
  root to: 'home#index'

  get 'home' => 'home#index'

  get 'courses' => 'courses#select'

  get 'enrollments/welcome' => 'enrollments#welcome'

  get '/tests/check' => 'tests#check'

  get 'teach' => 'teach#index'

  post 'mentorships/:id' => 'mentorships#show'

  get '/mentorships/user_video' => 'mentorships#user_video'

  get '/mentorships/tutor_video' => 'mentorships#tutor_video'

  resources :subjects, :only => [:index, :new, :create, :show]

  resources :courses, :only => [:index, :new, :create, :show]

  resources :users

  resources :tasks

  resources :mentorships

  resources :enrollments, :only => [:create, :index]

resources :courses do
  resources :tasks
  end

end

app/models/achievement.rb
class Achievement < ActiveRecord::Base
	belongs_to :badge
	belongs_to :user
end

app/models/badge.rb
class Badge < ActiveRecord::Base
	belongs_to :course
	has_many :achievements
	has_many :users, through: :achievements 
end

app/models/course.rb
class Course < ActiveRecord::Base
	belongs_to :subject
	has_many :tasks, dependent: :destroy
	has_one :badge
end

app/models/enrollment.rb
class Enrollment < ActiveRecord::Base
	belongs_to :user, :class_name => "User", :foreign_key => :user_id
	belongs_to :task, :class_name => "Task", :foreign_key => :task_id 

	has_one :mentorship
end

app/models/guide.rb
class Guide < ActiveRecord::Base
	belongs_to :module
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
	#for users who upload content
	belongs_to :user
	#for enrolled users
	has_many :enrollments
	has_many :enrolled_users, through: :enrollments, :source => :users
	#for module interaction with other resources
	belongs_to :course
	has_one :guide
	has_one :test
	#for distinguishing between authors and enrollees
	belongs_to :author, :class_name => "User"
	has_many :enrollees, :through => :Enrollments, :class_name => "User"
end

app/models/mentorship.rb
class Mentorship < ActiveRecord::Base
	belongs_to :enrollment 
	has_many :tasks, through: :enrollments

	belongs_to :tutor, :class_name => "User", :foreign_key => :tutor_id

	belongs_to :user

	
end

app/models/option.rb
class Option < ActiveRecord::Base
	belongs_to :question
end

app/models/question.rb
class Question < ActiveRecord::Base
	belongs_to :test
	has_many :options
end

app/models/subject.rb
class Subject < ActiveRecord::Base
	has_many :courses, dependent: :destroy
	has_many :tasks, :through => :courses
end

app/models/task.rb
class Task < ActiveRecord::Base
	#for users who upload content
	belongs_to :user
	#for enrolled users
	has_many :enrollments
	has_many :enrolled_users, through: :enrollments, :source => :users
	#for module interaction with other resources
	belongs_to :course
	has_one :guide
	has_one :test
	#for distinguishing between authors and enrollees
	belongs_to :author, :class_name => "User"
	has_many :enrollees, :through => :Enrollments, :class_name => "User"
end

app/models/test.rb
class Test < ActiveRecord::Base
	belongs_to :task
	has_many :questions
end

app/models/user.rb
class User < ActiveRecord::Base

  # Include default devise tasks. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	has_many :achievements
	has_many :badges, through: :achievements 
	#for users that will upload tasks
	has_many :created_tasks, :source => :tasks, :foreign_key => :author_id
	#for users who will enroll in tasks
	has_many :enrollments
	has_many :tasks, through: :enrollments
	
	has_many :mentorships
end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController
	 #forces the user to log in before doing anything at all
  before_action :authenticate_user!
	def new
		@badge = Badge.new
	end
end

app/controllers/guides_controller.rb
class GuidesController < ApplicationController
	 #forces the user to log in before doing anything at all
  	before_action :authenticate_user!
	def new
		@guide = Guide.new
	end

	def create
		@guide = Guide.new
		@guide.save
		redirect_to :action => :index
	end

	def guide_params
		params.require(:guide).permit()
	end	
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/tasks_controller.rb
 class TasksController < ApplicationController
 #forces the user to log in before doing anything at all
  	before_action :authenticate_user!

  	def index
		@tasks = Task.all
	end	

	def new
		@task = Task.new
	end

	def show
		@options = ["A", "B", "C", "D"]
		@task = Task.find(params[:id])
		unless current_user.tasks.include?(@task)
			@enrollment = Enrollment.new
			@enrollment.status = "In Progress"
			@enrollment.user_id = current_user.id
			@enrollment.task_id = params[:id]
			@enrollment.save
		end
		# if @enrollment.save
		# 	flash[:something] = "Enrollment successful!"
	end

	def create
		@task = Task.new(task_params)
		@task.save
		redirect_to :action => :index
	end
	
	def task_params
		params.require(:task).permit(:name, :points, :enrollee_id, :author_id, :description, :course_id)
	end	

end

app/controllers/teach_controller.rb
class TeachController < ApplicationController

	def index
		@enrollments = current_user.enrollments
		@mentorships = Mentorship.all
		@users = User.all
	end
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController
	 #forces the user to log in before doing anything at all
  	before_action :authenticate_user!
	def new
		@test = Test.new
	end

	def check
		@enrollment = current_user.enrollments.find_by_task_id(params[:task_id])
		@count = 0
		@score = 0
		@test = Test.find(params[:task_id])
		@test.questions.each do |q|
			if q.answer == params["question#{q.id}"]
				@score += 1
			end
			@count += 1
		end
		if @score == @count
			@enrollment.update_attribute(:status, "Complete")
		end
		# if @score == @count
		# 	current_user.points += @test.task.points
		# end
		# render "test/check", :layout => false
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	 #forces the user to log in before doing anything at all
  	before_action :authenticate_user!
	
	def index
		@user = User.all
		@enrollments = Enrollment.all
	end	

	def new
		@user = User.new
		@user.points = 0
	end

	def create
		@user = User.new(user_params)
		@user.points = 0
		@user.save
		redirect_to :action => :index
	end
	
	def user_params
		params.require(:user).permit(:name)
	end	
end

app/helpers/application_helper.rb
module ApplicationHelper
	def column_class
		if user_signed_in?
			"col-md-2 col-width-20"
		else
			"col-md-12"
		end
	end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<!-- <div class="main"> -->
	<div id="cloud-container"><div>
	
	<h1 class="head">Welcome to Canopy Connect!</h1>
	<%= link_to image_tag "logo.png", class: "logo" %>

	<% if user_signed_in? %>
		Welcome, <%= current_user.name %>!
	<% end %>

<!-- </div>
 -->

app/views/tasks/index.html.erb
<strong><h1>Tasks coming soon!</h1></strong>

<% @tasks.each do |task| %>
	<h3><%= task.id %>.
	<%= task.name %></h3>
	<br/>
	<strong>Description: </strong><%= task.description %>
	<br/>
    </br>
	<strong>Reward: </strong><%= task.points %> points
	<br/>
	<br/>
	<%= link_to 'ENROLL', enrollments_path, method: :post %>
<% end %>
<br/>

app/views/tasks/show.html.erb
<h1><%= @task.name %> Challenge</h1>
<div class = "row surround-upper-content">
	
	<div class = "col-md-5 text_box_for_enroll">
		<strong><h4 class= "inside-header">Description: </h4></strong>
		<div class = "text_body"><%= @task.description %>
		</div>
	</div>
	<div class = "col-md-12 text_box_for_enroll">
		<strong><h4 class= "inside-header">Read About It</h4></strong>
		<div class = "text_body">
			<% @task.guide.body.split(" ").each_with_index do |link, i|%>
			<%= link_to "Resource #{i+1}", link, class: "centered_links" %>
			<br/>
			<% end %>
		</div>
	</div>
	<div class = "col-md-12 text_box_for_enroll">
		<strong><h4 class= "inside-header">Practice</h4></strong>
		<div class = "text_body">
			<% @task.guide.practice.split(" ").each_with_index do |link, i|%>
			<%= link_to "Practice #{i+1}", link, class: "centered_links" %>
		<br/>
		<% end %>
		</div>
	</div>
</div>
	<div class= "wrapper-tutor-button">
		<%= link_to 'Connect With Tutor', mentorship_path, method: :post, class: "tutor-button" %>
	</div>
	<div class = "course-header" id = "buttons">
		<a class="test-button" href="#take_test">Take Test</a>
	</div>



<div class="take_test_view" id="take_test">

	<br/>
	<%= @task.test.body %>
	<br/><br/>
	<%= form_tag "/tests/check", id: "test_form" do %>
	<input type="hidden" name="task_id" value=<%= params[:id] %> >

	<ol>
		<% @task.test.questions.each do |question| %>
		<li><%= question.body %></li>
		<div class="questions">
			<% question.options.each_with_index do |option, index| %>
			<input type="radio" name=<%= "question#{question.id}" %> value="<%= @options[index] %>" class="answers">
			<%= @options[index] + ") " + option.body %>
			<br/>
			<% end %>
		</div>
		<% end %>
	</ol>
	<button class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal" id="ugly-submit">
	  Submit
	</button>
<!-- 	<input type="submit" name="Submit" value="Submit"> -->
	<% end %>
</div>



<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel"></h4>
      </div>
      <div class="modal-body">
      	<h1>Calculating Results...</h1>


      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal" >Close</button>
<!--        <%= link_to 'Profile', users_path %> -->
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<!-- Generate Profile Picture and Caption it with User Name -->

<div id="container"></div>

<h1 class= "welcome_message" id = "top">Welcome to your personal page, <%= "#{current_user.name.capitalize}" %>!</h1>

<div class="row">

	<div class="col-md-4 Link" id = "user_view_mode">
		<%=link_to image_tag("silhouette.jpg", class: "img-circle")  %></br>
		<%= "#{current_user.name.capitalize}"%>
	</div>
	<div class="col-md-4 Links">
		<%=link_to image_tag("shield.png") %></br>
		<a href="#badges", class = "Links">
			Badges
		</a>
	</div>


	<div class="col-md-4 Links">
		<%=link_to image_tag("enrollment.png") %></br>
		<a href="#progress", class = "Links">
			Progress
		</a>
	</div>

</div>

<div class = "row badge">
	<% badges = Badge.all %>

	<h2 id="badges">
		Badges
	</h2>

	<% badges.each do |badge| %>
	<div class= "col-md-3">
		<strong><%= badge.name %></strong></br></br>
		<%= image_tag("#{badge.icon}") %>	
	</div>	
	<% end %>

	<div class = "col-md-6"><a href="#top", class = "top_link">Back To Top</a></div>	
	<div class = "col-md-6"><a href="#progress", class = "top_link">View Progress</a></div>

</div>	
<div class = "progress badge"
	<div id="progress">
<% @enrollments.each do |e| %> 
	<% if e.user_id == current_user.id %>
	<% if e.status == "In Progress" %>
	<strong><h3>Task: </strong><%= e.task.name %></h3>
	<strong><h3>Status: </strong><%= e.status %></h3>
	<%= link_to 'View Course Page', "/tasks/#{e.task.id}" %>
	<% end %>
	<% end %>
<% end %>
</div>