config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  
  root to: 'home#index'

  get 'home' => 'home#index'

  get 'courses' => 'courses#select'

  get 'enrollments/welcome' => 'enrollments#welcome'

  get '/tests/check' => 'tests#check'

  get 'teach' => 'teach#index'

  post 'mentorships/:id' => 'mentorships#show'

  get '/mentorships/user_video' => 'mentorships#user_video'

  get '/mentorships/tutor_video' => 'mentorships#tutor_video'

  resources :subjects, :only => [:index, :new, :create, :show]

  resources :courses, :only => [:index, :new, :create, :show]

  resources :users

  resources :tasks

  resources :mentorships

  resources :enrollments, :only => [:create, :index]

resources :courses do
  resources :tasks
  end

end

app/models/achievement.rb
class Achievement < ActiveRecord::Base
	belongs_to :badge
	belongs_to :user
end

app/models/badge.rb
class Badge < ActiveRecord::Base
	belongs_to :course
	has_many :achievements
	has_many :users, through: :achievements 
end

app/models/course.rb
class Course < ActiveRecord::Base
	belongs_to :subject
	has_many :tasks, dependent: :destroy
	has_one :badge
end

app/models/enrollment.rb
class Enrollment < ActiveRecord::Base
	belongs_to :user, :class_name => "User", :foreign_key => :user_id
	belongs_to :task, :class_name => "Task", :foreign_key => :task_id 

	has_one :mentorship
end

app/models/guide.rb
class Guide < ActiveRecord::Base
	belongs_to :module
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
	#for users who upload content
	belongs_to :user
	#for enrolled users
	has_many :enrollments
	has_many :enrolled_users, through: :enrollments, :source => :users
	#for module interaction with other resources
	belongs_to :course
	has_one :guide
	has_one :test
	#for distinguishing between authors and enrollees
	belongs_to :author, :class_name => "User"
	has_many :enrollees, :through => :Enrollments, :class_name => "User"
end

app/models/mentorship.rb
class Mentorship < ActiveRecord::Base
	belongs_to :enrollment 
	has_many :tasks, through: :enrollments

	belongs_to :tutor, :class_name => "User", :foreign_key => :tutor_id

	belongs_to :user

	
end

app/models/option.rb
class Option < ActiveRecord::Base
	belongs_to :question
end

app/models/question.rb
class Question < ActiveRecord::Base
	belongs_to :test
	has_many :options
end

app/models/subject.rb
class Subject < ActiveRecord::Base
	has_many :courses, dependent: :destroy
	has_many :tasks, :through => :courses
end

app/models/task.rb
class Task < ActiveRecord::Base
	#for users who upload content
	belongs_to :user
	#for enrolled users
	has_many :enrollments
	has_many :enrolled_users, through: :enrollments, :source => :users
	#for module interaction with other resources
	belongs_to :course
	has_one :guide
	has_one :test
	#for distinguishing between authors and enrollees
	belongs_to :author, :class_name => "User"
	has_many :enrollees, :through => :Enrollments, :class_name => "User"
end

app/models/test.rb
class Test < ActiveRecord::Base
	belongs_to :task
	has_many :questions
end

app/models/user.rb
class User < ActiveRecord::Base

  # Include default devise tasks. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	has_many :achievements
	has_many :badges, through: :achievements 
	#for users that will upload tasks
	has_many :created_tasks, :source => :tasks, :foreign_key => :author_id
	#for users who will enroll in tasks
	has_many :enrollments
	has_many :tasks, through: :enrollments
	
	has_many :mentorships
end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController
	 #forces the user to log in before doing anything at all
  before_action :authenticate_user!
	def new
		@badge = Badge.new
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/mentorships_controller.rb
class MentorshipsController < ApplicationController

	def index
		@mentorships = Mentorship.all
	end

	def show
		# @mentorship = current_user.mentorships.find(params[:id])
		# unless current_user.mentorships.include?(@mentorship)
		@enrollment = Enrollment.find(params[:id])
			@mentorship = Mentorship.new
			@mentorship.status = "Pending"
			@mentorship.user_id = current_user.id
			@mentorship.enrollment_id = params[:id]
			@mentorship.save
		# end
	end

	# def create
	# 	# @mentorships = current_user.mentorships.find(params[:id])
	# 	# unless current_user.mentorships.include?(@mentorship)
	# 		@mentorship = Mentorship.new
	# 		@mentorship.status = "Pending"
	# 		@mentorship.user_id = current_user.id
	# 		@mentorship.task_id = params[:id]
	# 		@mentorship.save
	# end

	def update
		@mentorship = Mentorship.find(params[:id])
		@mentorship.tutor_id = current_user.id
		@mentorship.status = "Complete"
		@mentorship.save
	end

	def tutor_video
	end

	def user_video
	end
end

app/controllers/tasks_controller.rb
 class TasksController < ApplicationController
 #forces the user to log in before doing anything at all
  	before_action :authenticate_user!

  	def index
		@tasks = Task.all
	end	

	def new
		@task = Task.new
	end

	def show
		@options = ["A", "B", "C", "D"]
		@task = Task.find(params[:id])
		unless current_user.tasks.include?(@task)
			@enrollment = Enrollment.new
			@enrollment.status = "In Progress"
			@enrollment.user_id = current_user.id
			@enrollment.task_id = params[:id]
			@enrollment.save
		end
		# if @enrollment.save
		# 	flash[:something] = "Enrollment successful!"
	end

	def create
		@task = Task.new(task_params)
		@task.save
		redirect_to :action => :index
	end
	
	def task_params
		params.require(:task).permit(:name, :points, :enrollee_id, :author_id, :description, :course_id)
	end	

end

app/controllers/teach_controller.rb
class TeachController < ApplicationController

	def index
		@enrollments = current_user.enrollments
		@mentorships = Mentorship.all
		@users = User.all
	end
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController
	 #forces the user to log in before doing anything at all
  	before_action :authenticate_user!
	def new
		@test = Test.new
	end

	def check
		@enrollment = current_user.enrollments.find_by_task_id(params[:task_id])
		@count = 0
		@score = 0
		@test = Test.find(params[:task_id])
		@test.questions.each do |q|
			if q.answer == params["question#{q.id}"]
				@score += 1
			end
			@count += 1
		end
		if @score == @count
			@enrollment.update_attribute(:status, "Complete")
		end
		# if @score == @count
		# 	current_user.points += @test.task.points
		# end
		# render "test/check", :layout => false
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	 #forces the user to log in before doing anything at all
  	before_action :authenticate_user!
	
	def index
		@user = User.all
		@enrollments = Enrollment.all
	end	

	def new
		@user = User.new
		@user.points = 0
	end

	def create
		@user = User.new(user_params)
		@user.points = 0
		@user.save
		redirect_to :action => :index
	end
	
	def user_params
		params.require(:user).permit(:name)
	end	
end

app/helpers/application_helper.rb
module ApplicationHelper
	def column_class
		if user_signed_in?
			"col-md-2 col-width-20"
		else
			"col-md-12"
		end
	end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/mentorships/create.html.erb
<h1>MENTORSHIP CREATE PAGE</h1>

<% mentorships = Mentorship.all %>

<% mentorships.each do |m| %>
<%= m.status %>
<%= m.user.name %>
<% end %>

app/views/mentorships/index.html.erb
<h1>Your Connections</h1>


<div class = "text_box_for_teach">
	<% @mentorships.each_with_index do |m, i| %>
	<% if m.user_id == current_user.id %>
		<div class="I_hate_cameron">
			<div class = "task_name_for_teach"><%= i+1 %>) <%= m.enrollment.task.name %></div>
			<!-- Handle cases with no tutor -->
				<% if m.tutor == nil %>
					<div class = 'link_for_teach_page'><%= "Sorry, nobody has connected with you yet, stay tuned!" %></div>
					<% m.status %>
					<% break %>
				<% else %>	
					<div class = 'link_for_teach_page'>Your Partner: <%= m.user.name %></div>
					<div class = 'task_help_for_teach'><%= link_to 'View Team Page', "/mentorships/tutor_video", method: :get %></div>

				<% end %>
	<% end %>	
		<% if m.tutor_id == current_user.id %>
			<div class = 'link_for_teach_page'>Your Partner: <%= m.user.name %></div>
			<div class = 'task_help_for_teach'><%= link_to 'View Team Page', "/mentorships/tutor_video", method: :get %></div>
			<% else %>
			<div class = 'link_for_teach_page'><%= m.tutor.name %></div class = 'link_for_teach_page'>
			<%= link_to 'View Team Page', "/mentorships/user_video", method: :get, :class => 'task_help_for_teach' %>
			<% end %>
		</div>
	<% end %>

</div>

app/views/mentorships/show.html.erb
<h1>Tutor Requested For <strong><%= @enrollment.task.name %></h1></strong>

<!-- Insert some message letting the user know how tutorships work -->

<h3>Someone will connect with you soon!</h3>

app/views/mentorships/tutor_video.html.erb
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Testing OpenTok</title>
    <script src="//static.opentok.com/webrtc/v2.2/js/opentok.min.js" ></script>
</head>
<body>

    <script type="text/javascript">
        var apiKey = "44892631";
        var sessionID = "2_MX40NDg5MjYzMX5-V2VkIEp1bCAwOSAxNDowOTo0NyBQRFQgMjAxNH4wLjA0MjIxNTg4NH5-";
        var token = "T1==cGFydG5lcl9pZD00NDg5MjYzMSZzaWc9OTZjYjRjZWM0NDY5ODFiZTUyNGE2Y2ZlYTUyMGI3MTVkOGZiNjg5Zjpyb2xlPXB1Ymxpc2hlciZzZXNzaW9uX2lkPTJfTVg0ME5EZzVNall6TVg1LVYyVmtJRXAxYkNBd09TQXhORG93T1RvME55QlFSRlFnTWpBeE5INHdMakEwTWpJeE5UZzROSDUtJmNyZWF0ZV90aW1lPTE0MDQ5NDAxOTUmbm9uY2U9MC42ODg1ODE1OTU2MzMwMDg3JmV4cGlyZV90aW1lPTE0MDc1MzIxNzk=";
        var session = OT.initSession(apiKey, sessionID);
        session.on("sessionConnected", function sessionConnectHandler(event) {
           var publisher = OT.initPublisher("publisher",{width:300, height:250});
            session.publish(publisher);
        });
        session.on("streamCreated", function(event) {
            var subscriber = session.subscribe(event.stream, "subscribeContainer", {width:448, height:336});
        });
        session.connect(token);
        var publisher;

        function unpublish() {
            session.unpublish(publisher);
        }
    </script>


<div id="publisher"></div>

</body>

</html>



<!-- T1==cGFydG5lcl9pZD00NDg5MjQ3MiZzaWc9OGMwZDllMmRlYzNjMzEzMDJmNmI5Zjg3MWViNGIzODkxYTlhNWJmMTpyb2xlPXB1Ymxpc2hlciZzZXNzaW9uX2lkPTJfTVg0ME5EZzVNalEzTW41LVYyVmtJRXAxYkNBd09TQXhNem93T0Rvd09DQlFSRlFnTWpBeE5INHdMalV3T0Rnd05qbC1mZyZjcmVhdGVfdGltZT0xNDA0OTM3MDQxJm5vbmNlPTAuNjg1NTA4Njc3MDM5NDE2MyZleHBpcmVfdGltZT0xNDA3NTI4NDY5 -->

app/views/mentorships/update.html.erb
<h1>You've been connected with <%= @mentorship.user.name %>!</h1>


<h1><%= link_to 'See Your Connections', mentorships_path %></h1>

app/views/mentorships/user_video.html.erb
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Testing OpenTok</title>
    <script src="//static.opentok.com/webrtc/v2.2/js/opentok.min.js" ></script>
</head>
<body>

    <script type="text/javascript">
        var apiKey = "44892631";
        var sessionID = "2_MX40NDg5MjYzMX5-V2VkIEp1bCAwOSAxNDowOTo0NyBQRFQgMjAxNH4wLjA0MjIxNTg4NH5-";
        var token = "T1==cGFydG5lcl9pZD00NDg5MjYzMSZzaWc9OTYwNzcyMjJmNzc2ZWVkNTQ0MjE5M2I1NjlmZjhiMjViMTc1NWEyYjpyb2xlPXB1Ymxpc2hlciZzZXNzaW9uX2lkPTJfTVg0ME5EZzVNall6TVg1LVYyVmtJRXAxYkNBd09TQXhORG93T1RvME55QlFSRlFnTWpBeE5INHdMakEwTWpJeE5UZzROSDUtJmNyZWF0ZV90aW1lPTE0MDQ5NDAyNTgmbm9uY2U9MC42OTI4Mzc4MTkwMzkzNTE1JmV4cGlyZV90aW1lPTE0MDc1MzIxNzk=";
        var session = OT.initSession(apiKey, sessionID);
        session.on("sessionConnected", function sessionConnectHandler(event) {
           var publisher = OT.initPublisher("publisher",{width:500, height:450});
            session.publish(publisher);
        });
        session.on("streamCreated", function(event) {
            var subscriber = session.subscribe(event.stream, "subscribeContainer", {width:448, height:336});
        });
        session.connect(token);
        var publisher;

        function unpublish() {
            session.unpublish(publisher);
        }
    </script>

<div id="publisher"></div>

</body>
</html>








<!-- T1==cGFydG5lcl9pZD00NDg5MjQ3MiZzaWc9OWVkZTA0ODlmOWE1YmIzMjhiMjFhZGEwMGYxNDAwZDI5MTJiM2JmNDpyb2xlPXB1Ymxpc2hlciZzZXNzaW9uX2lkPTJfTVg0ME5EZzVNalEzTW41LVYyVmtJRXAxYkNBd09TQXhNem93T0Rvd09DQlFSRlFnTWpBeE5INHdMalV3T0Rnd05qbC1mZyZjcmVhdGVfdGltZT0xNDA0OTM2NTA0Jm5vbmNlPTAuNDQ2Mjc5Nzg2Njc0Njk1NyZleHBpcmVfdGltZT0xNDA3NTI4NDY5 -->